Further split the EMR release migrations to prevent errors.
The errors read like this:

   psycopg2.OperationalError: cannot ALTER TABLE "clusters_cluster" because it has pending trigger events